#Autor: LAH
#Version 1.0

# Set the base image
FROM node:16.13.1

# Create and set the working directory
WORKDIR /hello-world

# Copy the package.json and package-lock.json files
COPY package*.json ./

RUN npm install

# Copy the entire project to the container
COPY . .

EXPOSE 3000

CMD ["npm", "start"]
