FROM node:16.13.1-alpine AS build

WORKDIR /tmp/build

COPY . .

RUN npm i -g npm; npm i; npm run build

FROM nginx AS final

WORKDIR /usr/share/nginx/html

RUN apt-get update  -y \
    && apt-get upgrade -y \ 
    && apt-get install -y \
    ssh \
    sshpass \
    sudo \
    software-properties-common \
    gpg

RUN add-apt-repository --yes --update ppa:ansible/ansible \
    && apt-get install -y ansible

COPY --from=build /tmp/build/build .

WORKDIR /home/controller_node

COPY startup.sh .
