name: CI Java Pipeline

on:
    pull_request:
        branches:
            - main

jobs:
    build_test_app:
        runs-on: ubuntu-latest

        steps: 
            - name: Checkout Code
              uses: actions/checkout@v4

            - uses: actions/setup-java@v5
              with:
                distribution: 'temurin'
                java-version: '21'
                cache: maven
            
            - name: Build project
              run: |
                ./mvnw clean package -DskipTests
              working-directory: itj-shopping-cart

            - name: Run tests
              run: |
                ./mvnw test
              working-directory: itj-shopping-cart

    deploy_java_app:
        needs: build_test_app
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Install Heroku CLI
              run: |
                curl https://cli-assets.heroku.com/install.sh | sh

            - uses: akhileshns/heroku-deploy@v3.14.15 # This is the action
              with:
                heroku_api_key: ${{ secrets.HEROKU_API_KEY_SWEBP }}
                heroku_app_name: "itj-shopping-cart-swebp" #Must be unique in Heroku
                heroku_email: ${{ vars.HEROKU_USERNAME_SWEBP }}
                appdir: "itj-shopping-cart"
                usedocker: true



