# Every PR
## Build app
## Run tests
## Deploy to dev environment
name: CI/CD on Pull Request

on:
    pull_request:
      branches:
        - main

jobs:
  build_test_app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: maven
      
      - name: Build project
        run: ./mvnw clean package -DskipTests
        working-directory: itj-shopping-cart

      - name: Run tests
        run: ./mvnw test
        working-directory: itj-shopping-cart
            