name: github actions

on:
  push: 
  pull_request:
  workflow_dispatch:

jobs:
    github_act:
              name: testing
              runs-on: macos-latest
              steps: 
              - name: step one
                uses: actions/checkout@v3
              - name: step two
                run: |
                  cd capstone_project/hello-world/
                  npm install
                  npm test
                  echo "Testing successful"
                  
    build_dockerfile:
                     needs: [github_act]
                     name: build dockerfile 
                     runs-on: ubuntu-latest
                     steps:
                     - name: build the environment
                       uses: actions/checkout@v3
                     - name: install docker
                       run: |
                         sudo apt-get update
                         sudo apt-get install apt-transport-https ca-certificates curl gnupg-agent software-properties-common
                         curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
                     - name: checking docker
                       run: docker -v
                     - name: build container
                       run: |
                         cd capstone_project/hello-world/
                         docker build -t capstone_p .
                     - name: check image
                       run: docker image ls 
