name: github actions

on:
  push: 
  pull_request:
  workflow_dispatch:

jobs:
    github_act:
              name: testing
              runs-on: macos-latest
              steps: 
              - name: step one
                uses: actions/checkout@v3
              - name: step two
                run: |
                  cd capstone_project/hello-world/
                  npm install
                  npm test
                  echo "Testing successful"
                  
    build_dockerfile:
                     needs: [github_act]
                     name: build dockerfile 
                     runs-on: ubuntu-latest
                     steps:
                     - name: build the environment
                       uses: actions/checkout@v3
                     - name: build dockerfile
                       run: |
                         cd capstone_project/hello-world/
                         /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
                         brew install docker
                         docker build . --file Dockerfile --tag capstone_p:$(date +%s)
