name: github actions

on:
  push: 
  pull_request:
  workflow_dispatch:

jobs:
    github_act:
              name: firstaction
              runs-on: macos-latest
              steps: 
              - name: step one
                uses: actions/checkout@v3
              - name: step two
                run: |
                  npm test
                  echo "Testing successful"
