name: My workflow 
on: push

jobs:
  job1:
    name: First job
    runs-on: ubuntu-latest
    steps:
      - name: First tasks
      uses: actions/checkout@v2
      - name : Second tasks
      run: |
        echo TEST