name:  wot
on: push

jobs:
    job1:
      name: First job
      runs-on: ubuntu-latest
      steps:
        - name: Step One
          uses: actions/checkout@v2
        - name: Step Two
          run: |
            touch ${{ secrets.MYREPOSECRET }}.yaml
            echo "my first touch" >>  ${{ secrets.MYREPOSECRET }}.yaml
            cat ${{ secrets.MYREPOSECRET }}.yaml 
            pwd

    job2:
      name: Second job
      runs-on: windows-latest
      steps:
        - name: Step one
          uses: actions/checkout@v2
        - name: Step two
          run: date

    job3:
      name: Third job
      needs: [job1 ]
      runs-on: macos-latest
      steps:
        - name: Step one
          uses: actions/checkout #clone repo
        - name: Step two
          run: |
            date
            touch ${{ secrets.MYREPOSECRET }}.yaml