name: CI Papline

on:
  push:
  pull_request:
  
jobs:
  jobimage:
    runs-on: ubuntu-latest
    steps:
      - name: Step One Check Rout
        uses: actions/checkout@v2
        with:
          path: capstone_project
      - name: Step Two Dependencies
        working-directory: /hello-world/
        run: npm install
      - name: Step Three 
        working-directory: /hello-world/
        run: npm test
      - name: Build and push Docker image
        working-directory: /hello-world/
        run: |
          docker build -t hello-world .
          docker push hello-world
      
  
  
