name: DDD Bootcamp workflow

on: push

jobs:
    job1:
      name: Second job
      runs-on: windows-latest
      steps:
        - name: Step one
          uses: actions/checkout@v2
        - name: Step two
          run: date

    job2:
      name: Third job
      needs: [job1 ]
      runs-on: macos-latest
      steps:
        - name: Step one
          uses: actions/checkout #clone repo
        - name: Step two
          run: |
            date
            touch test.txt